@startuml
mainframe sd "Couper"

actor Utilisateur

participant InterfaceUtilisateur
participant Bouton
participant Couper
participant EditeurBuffer
participant PressePapier

Utilisateur -> InterfaceUtilisateur :Clic sur le bouton "Couper"
activate InterfaceUtilisateur

InterfaceUtilisateur -> Bouton ++ :executeCommand()
Bouton -> Couper --: execute()
activate Couper
activate EditeurBuffer

Couper -> EditeurBuffer : getSelection()
EditeurBuffer --> Couper : retourne le texte sélectionné
Couper -> PressePapier: setContenu(texte)

Couper -> EditeurBuffer :efface la sélection (texte = "")
deactivate Couper

EditeurBuffer --> InterfaceUtilisateur : mise à jour de l'affichage du texte
deactivate EditeurBuffer
deactivate InterfaceUtilisateur
@enduml